CREATE TABLE IF NOT EXISTS ustads (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS subjects (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS monthly_plan (
  id INT AUTO_INCREMENT PRIMARY KEY,
  month_name VARCHAR(32) NOT NULL,
  ustad_name VARCHAR(120) NOT NULL,
  week VARCHAR(40) NOT NULL,
  total_period VARCHAR(40) NOT NULL,
  subject VARCHAR(120) NOT NULL,
  lesson_name VARCHAR(255) NOT NULL,
  lesson_details TEXT NULL,
  activities TEXT NULL,
  smart_date DATE NULL,
  exam_date DATE NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
