<?php if ( ! defined( 'ABSPATH' ) ) { exit; } ?><!doctype html>
<html <?php language_attributes(); ?> data-theme="<?php echo esc_attr( get_theme_mod( 'amia_dark_mode_default', true ) ? 'dark' : 'light' ); ?>">
<head><meta charset="<?php bloginfo( 'charset' ); ?>"><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"><?php wp_head(); ?></head>
<body <?php body_class( 'amia-loading' ); ?>><?php wp_body_open(); ?>
<header class="amia-site-header">
	<div class="amia-container amia-navbar">
		<a class="amia-brand" href="<?php echo esc_url( home_url( '/' ) ); ?>"><?php amia_premium_brand(); ?></a>
		<nav class="amia-primary-menu" aria-label="<?php esc_attr_e( 'Primary menu', 'amia-gallery-premium' ); ?>"><?php wp_nav_menu( array( 'theme_location' => 'primary', 'container' => false, 'menu_class' => 'amia-menu', 'fallback_cb' => false ) ); ?></nav>
		<div class="amia-actions"><button class="amia-icon-btn amia-search-toggle" aria-label="<?php esc_attr_e( 'Search', 'amia-gallery-premium' ); ?>">⌕</button><button class="amia-icon-btn amia-theme-toggle" aria-label="<?php esc_attr_e( 'Toggle theme', 'amia-gallery-premium' ); ?>">◐</button><button class="amia-icon-btn amia-notification-toggle" aria-label="<?php esc_attr_e( 'Notifications', 'amia-gallery-premium' ); ?>">🔔<span class="amia-notification-badge is-zero">0</span></button><?php if ( is_user_logged_in() ) : ?><button class="amia-icon-btn amia-profile-toggle"><img src="<?php echo esc_url( amia_premium_user_image() ); ?>" alt="" width="28" height="28"></button><?php else : ?><a class="amia-btn" href="<?php echo esc_url( wp_login_url() ); ?>"><?php esc_html_e( 'Login', 'amia-gallery-premium' ); ?></a><?php endif; ?><button class="amia-menu-toggle" aria-label="<?php esc_attr_e( 'Menu', 'amia-gallery-premium' ); ?>">☰</button></div>
	</div>
	<div class="amia-dropdown amia-glass amia-profile-dropdown"><a href="<?php echo esc_url( get_edit_profile_url() ); ?>"><?php esc_html_e( 'Profile', 'amia-gallery-premium' ); ?></a><a href="<?php echo esc_url( wp_logout_url( home_url() ) ); ?>"><?php esc_html_e( 'Logout', 'amia-gallery-premium' ); ?></a></div>
</header>
<aside class="amia-notification-drawer amia-glass" aria-label="<?php esc_attr_e( 'Notification center', 'amia-gallery-premium' ); ?>"><div class="amia-drawer-head"><div><span class="amia-kicker"><?php esc_html_e( 'View only', 'amia-gallery-premium' ); ?></span><h2><?php esc_html_e( 'Live Notifications', 'amia-gallery-premium' ); ?></h2></div><button class="amia-icon-btn amia-notification-toggle" type="button">×</button></div><div class="amia-notification-tools"><input class="amia-notification-search" type="search" placeholder="<?php esc_attr_e( 'Search notifications', 'amia-gallery-premium' ); ?>"><select class="amia-notification-category"><option value="all"><?php esc_html_e( 'All', 'amia-gallery-premium' ); ?></option><option value="users"><?php esc_html_e( 'Users', 'amia-gallery-premium' ); ?></option><option value="uploads"><?php esc_html_e( 'Uploads', 'amia-gallery-premium' ); ?></option><option value="security"><?php esc_html_e( 'Security', 'amia-gallery-premium' ); ?></option><option value="settings"><?php esc_html_e( 'Settings', 'amia-gallery-premium' ); ?></option></select><label class="amia-sound"><input type="checkbox" class="amia-sound-toggle"> <?php esc_html_e( 'Sound', 'amia-gallery-premium' ); ?></label><button class="amia-btn amia-btn-ghost amia-mark-read" type="button"><?php esc_html_e( 'Mark read', 'amia-gallery-premium' ); ?></button></div><div class="amia-live-notifications"><div class="amia-skeleton"></div><div class="amia-skeleton"></div></div></aside>
<div class="amia-search-popup"><div class="amia-search-panel amia-glass"><span class="amia-kicker">Ctrl / ⌘ + K</span><input type="search" class="amia-ajax-search" placeholder="<?php esc_attr_e( 'Search users, reports, gallery, pages...', 'amia-gallery-premium' ); ?>"><div class="amia-search-results"></div></div></div>
<main id="primary" class="site-main">
