<?php
/* Template Name: Reports */
get_header();
get_template_part( 'partials/dashboard-shell' );
$analytics = amia_premium_dashboard_analytics();
$export_url = add_query_arg( array( 'action' => 'amia_export_report', 'nonce' => wp_create_nonce( 'amia_theme_nonce' ) ), admin_url( 'admin-post.php' ) );
?>
<section class="amia-dashboard-hero amia-glass"><div><span class="amia-kicker"><?php esc_html_e( 'Advanced Reporting', 'amia-gallery-premium' ); ?></span><h1><?php esc_html_e( 'Reports & Intelligence', 'amia-gallery-premium' ); ?></h1><p class="amia-muted"><?php esc_html_e( 'User, upload, login, activity, device and browser reporting with export actions.', 'amia-gallery-premium' ); ?></p></div><div class="amia-hero-actions"><a class="amia-btn" href="<?php echo esc_url( $export_url ); ?>"><?php esc_html_e( 'Export CSV', 'amia-gallery-premium' ); ?></a><button class="amia-btn amia-btn-ghost" onclick="window.print()" type="button"><?php esc_html_e( 'Export PDF', 'amia-gallery-premium' ); ?></button></div></section>
<div class="amia-report-filters amia-glass"><label><?php esc_html_e( 'From', 'amia-gallery-premium' ); ?><input type="date"></label><label><?php esc_html_e( 'To', 'amia-gallery-premium' ); ?><input type="date"></label><label><?php esc_html_e( 'Role', 'amia-gallery-premium' ); ?><select><option><?php esc_html_e( 'All roles', 'amia-gallery-premium' ); ?></option><option>student</option><option>ustad</option><option>admin</option></select></label><button class="amia-btn amia-btn-ghost" type="button"><?php esc_html_e( 'Apply Filters', 'amia-gallery-premium' ); ?></button></div>
<section class="amia-bento-grid amia-live-dashboard"><article class="amia-bento-card"><h2><?php esc_html_e( 'User Reports', 'amia-gallery-premium' ); ?></h2><div class="amia-growth-chart"></div></article><article class="amia-bento-card"><h2><?php esc_html_e( 'Upload Reports', 'amia-gallery-premium' ); ?></h2><div class="amia-upload-chart"></div></article><article class="amia-bento-card"><h2><?php esc_html_e( 'Login Reports', 'amia-gallery-premium' ); ?></h2><div class="amia-login-chart"></div></article><article class="amia-bento-card"><h2><?php esc_html_e( 'Activity Reports', 'amia-gallery-premium' ); ?></h2><div class="amia-activity-chart"></div></article><article class="amia-bento-card"><h2><?php esc_html_e( 'Device Reports', 'amia-gallery-premium' ); ?></h2><div class="amia-device-chart"></div></article><article class="amia-bento-card"><h2><?php esc_html_e( 'Browser Reports', 'amia-gallery-premium' ); ?></h2><div class="amia-browser-chart"></div></article></section>
<?php get_template_part( 'partials/dashboard-end' ); get_footer(); ?>
