<?php if ( ! defined( 'ABSPATH' ) ) { exit; } ?>
<div class="agum-form-grid">
	<label>Student ID<input name="student_id" type="text"></label>
	<label>Admission No<input name="admission_no" type="text"></label>
	<label>Name<input name="name" type="text" required></label>
	<label>Class<input name="class" type="text"></label>
	<label>DOB<input name="dob" type="date"></label>
	<label>Role<select name="role"><option value="student">Student → Subscriber</option><option value="ustad">Ustad → Editor</option><option value="admin">Admin → Administrator</option><option value="superadmin">Superadmin → Administrator</option><option value="staff">Staff → Subscriber</option></select></label>
	<label>Username<input name="username" type="text" required></label>
	<label>Email<input name="email" type="email" placeholder="Optional; unique placeholder generated if blank"></label>
	<label>Password<input name="password" type="password" placeholder="Required for new users; autogenerated if blank"></label>
	<label>Phone Number<input name="phone_number" type="tel" pattern="\+?[0-9]{7,15}"></label>
	<label>Telegram Username<input name="telegram_username" type="text"></label>
	<label>Telegram ID<input name="telegram_id" type="text"></label>
	<label>User Photo<input name="user_image" type="file" accept=".jpg,.jpeg,.png,.webp,image/jpeg,image/png,image/webp"></label>
	<input name="image_path" type="hidden">
</div>
<div class="agum-preview"></div>
