<?php if ( ! defined( 'ABSPATH' ) ) { exit; } ?>
<div class="agum-app" data-theme="dark">
<aside class="agum-sidebar"><div class="agum-brand"><span class="agum-logo">A</span><div><strong>AMIA Gallery</strong><small>Imports & Media</small></div></div><nav><a href="<?php echo agum_admin_url( 'agum-dashboard' ); ?>">🏠 Dashboard</a><a href="<?php echo agum_admin_url( 'agum-users' ); ?>">👥 Users</a><a href="<?php echo agum_admin_url( 'agum-csv' ); ?>">📤 CSV Upload</a><a href="<?php echo agum_admin_url( 'agum-media' ); ?>">🖼 Media Upload</a><a href="<?php echo agum_admin_url( 'agum-settings' ); ?>">⚙ Settings</a></nav></aside>
<main class="agum-main"><header class="agum-topbar"><button class="agum-menu-toggle" type="button">☰</button><div><h1><?php echo 'csv' === $type ? esc_html__( 'Bulk CSV Upload', 'amia-gallery-user-manager' ) : esc_html__( 'User Image Upload', 'amia-gallery-user-manager' ); ?></h1><p>Validate, import and map user data securely.</p></div></header>
<?php if ( 'csv' === $type ) : $report = get_transient( 'agum_last_import_report_' . get_current_user_id() ); ?>
<section class="agum-card"><h2>Advanced CSV Import</h2><p>Required fields: <?php echo esc_html( implode( ', ', AGUM_CSV::expected_headers() ) ); ?></p><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" enctype="multipart/form-data" class="agum-upload-zone"><input type="hidden" name="action" value="agum_csv_import"><?php wp_nonce_field( AGUM_Security::NONCE_ACTION, AGUM_Security::NONCE_NAME ); ?><input type="file" name="csv_file" accept=".csv,text/csv" required><div class="agum-progress"><span></span></div><button class="agum-btn" type="submit">Import CSV</button></form></section>
<?php if ( $report && ! is_wp_error( $report ) ) : ?><section class="agum-card"><h2>Import Report</h2><div class="agum-grid"><div class="agum-stat"><span>Created</span><strong><?php echo esc_html( $report['created'] ); ?></strong></div><div class="agum-stat"><span>Skipped</span><strong><?php echo esc_html( $report['skipped'] ); ?></strong></div></div><ul class="agum-errors"><?php foreach ( $report['errors'] as $error ) : ?><li><?php echo esc_html( $error ); ?></li><?php endforeach; ?></ul></section><?php endif; ?>
<?php else : ?>
<section class="agum-card"><h2>Secure Media Upload</h2><p>Images are renamed to the selected user's normalized database name, e.g. MUHAMMED_SINAN.jpg.</p><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" enctype="multipart/form-data" class="agum-upload-zone"><input type="hidden" name="action" value="agum_media_upload"><?php wp_nonce_field( AGUM_Security::NONCE_ACTION, AGUM_Security::NONCE_NAME ); ?><select name="user_id" required><?php foreach ( $users['items'] as $user ) : ?><option value="<?php echo esc_attr( $user->id ); ?>"><?php echo esc_html( $user->name . ' (' . $user->username . ')' ); ?></option><?php endforeach; ?></select><input type="file" name="user_image" accept=".jpg,.jpeg,.png,.webp,image/jpeg,image/png,image/webp" required><div class="agum-preview"></div><button class="agum-btn" type="submit">Upload & Map Image</button></form></section>
<?php endif; ?></main></div><div class="agum-toast" aria-live="polite"></div>
