<?php
function initialize_card_schema(mysqli $conn): void
{
    $queries = [
        "CREATE TABLE IF NOT EXISTS card_templates (
            id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            template_name VARCHAR(120) NOT NULL,
            main_heading VARCHAR(255) NOT NULL,
            sub_heading VARCHAR(255) DEFAULT '',
            footer_text VARCHAR(255) DEFAULT '',
            field_config JSON NOT NULL,
            card_width_mm DECIMAL(6,2) NOT NULL DEFAULT 180.00,
            card_height_mm DECIMAL(6,2) NOT NULL DEFAULT 115.00,
            cards_per_page TINYINT UNSIGNED NOT NULL DEFAULT 2,
            is_default TINYINT(1) NOT NULL DEFAULT 0,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS card_settings (
            id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            setting_key VARCHAR(100) NOT NULL UNIQUE,
            setting_value TEXT NULL,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS card_exports (
            id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            export_type ENUM('pdf','excel','print') NOT NULL,
            template_id INT UNSIGNED NULL,
            student_count INT UNSIGNED NOT NULL DEFAULT 0,
            file_name VARCHAR(255) DEFAULT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            INDEX(template_id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS card_logs (
            id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            action VARCHAR(80) NOT NULL,
            details TEXT NULL,
            ip_address VARCHAR(45) DEFAULT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"
    ];

    foreach ($queries as $sql) {
        $conn->query($sql);
    }

    $defaultFields = json_encode([
        'name' => 1,
        'class' => 1,
        'admission_no' => 0,
        'register_num' => 1,
        'chest_no' => 1,
        'section' => 0,
        'house_name' => 0,
        'phone' => 0,
        'item_type' => 0,
    ], JSON_UNESCAPED_UNICODE);

    $count = 0;
    $result = $conn->query('SELECT COUNT(*) AS total FROM card_templates');
    if ($result) {
        $row = $result->fetch_assoc();
        $count = (int)($row['total'] ?? 0);
    }

    if ($count === 0) {
        $stmt = $conn->prepare('INSERT INTO card_templates (template_name, main_heading, sub_heading, footer_text, field_config, is_default) VALUES (?, ?, ?, ?, ?, 1)');
        $templateName = 'Default Exam Card';
        $mainHeading = 'ANNUAL EXAMINATION';
        $subHeading = 'MIFTAHUL HUDA MADRASA';
        $footer = 'Generated by Card Admin System';
        $stmt->bind_param('sssss', $templateName, $mainHeading, $subHeading, $footer, $defaultFields);
        $stmt->execute();
        $stmt->close();
    }

    $settings = [
        'institution_name' => 'MIFTAHUL HUDA MADRASA',
        'default_cards_per_page' => '2',
        'print_page_size' => 'A4',
        'admin_title' => 'Student Card Admin',
    ];
    foreach ($settings as $key => $value) {
        $stmt = $conn->prepare('INSERT IGNORE INTO card_settings (setting_key, setting_value) VALUES (?, ?)');
        $stmt->bind_param('ss', $key, $value);
        $stmt->execute();
        $stmt->close();
    }
}
