CREATE TABLE IF NOT EXISTS card_templates (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    template_name VARCHAR(120) NOT NULL,
    main_heading VARCHAR(255) NOT NULL,
    sub_heading VARCHAR(255) DEFAULT '',
    footer_text VARCHAR(255) DEFAULT '',
    field_config JSON NOT NULL,
    card_width_mm DECIMAL(6,2) NOT NULL DEFAULT 180.00,
    card_height_mm DECIMAL(6,2) NOT NULL DEFAULT 115.00,
    cards_per_page TINYINT UNSIGNED NOT NULL DEFAULT 2,
    is_default TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS card_settings (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    setting_key VARCHAR(100) NOT NULL UNIQUE,
    setting_value TEXT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS card_exports (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    export_type ENUM('pdf','excel','print') NOT NULL,
    template_id INT UNSIGNED NULL,
    student_count INT UNSIGNED NOT NULL DEFAULT 0,
    file_name VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX(template_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS card_logs (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    action VARCHAR(80) NOT NULL,
    details TEXT NULL,
    ip_address VARCHAR(45) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
